name: build-app
on: push
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - run: ./gradlew clean check assemble
      - uses: actions/upload-artifact@v4
        with:
          name: reports
          path: build/reports
      - uses: actions/upload-artifact@v4
        with:
          name: app-war-file
          path: build/libs/ROOT.war
